sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  # Run PHP lint on all PHP files.
  - find -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run the tests
  - php Runner.php
